service:
  name: graphql-poc
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
#  environment:
#    NODE_PATH: "./:/opt/node_modules"

layers:
  graphql_poc-node_modules:
    package:
      artifact: lambda_layer.zip
#    path: node_modules # required, path to layer contents on disk
    name: graphql_poc-node_modules # optional, Deployed Lambda layer name
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs8.10
#    licenseInfo: GPLv3 # optional, a string specifying license information
#    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
#      - '*'
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created

functions:
  api:
    handler: handler.graphql
    layers:
      - { Ref: GraphqlUnderscorepocDashnodeUnderscoremodulesLambdaLayer }
    events:
      - http:
          method: any
          path: graphql
