service:
  name: graphql-poc
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-layers

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: graphql-poc-serverless

functions:
  api:
    handler: src/server.graphql
    events:
      - http:
          method: any
          path: graphql
          cors: true

custom:
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: false
      heapInitial: 200m
      heapMax: 1g
      migrate: false
      seed: false
      convertEmptyValues: false
    seed:
      domain:
        sources:
          - table: GraphqlPoc
            sources: [./src/_common/database/seeds/users.json]
  serverless-layers:
    packageManager: yarn
    compileDir: .serverless
    packagePath: package.json
    compatibleRuntimes: ['nodejs']
